### ISSUE TITLE
Loot AWKCR Obsolete Message

### ISSUE THREAD

**Issue by clydemack** [loot/fallout4#143] opened 2020-02-18 07:52 UTC
ArmorKeywords.esm 8.6.0 CE32A0AE
Obsolete. Update to latest version.

That is the latest version. I have completely deleted the esm file. Downloaded it again. Installed it from scratch. Same error message.

Any suggestions?

Can I just ignore the warning?

**Comment by MacSplody** [comment] 2020-02-18 08:06
> Can I just ignore the warning?

You can ignore for now, until it can be looked at.

**Comment by MacSplody** [comment] 2020-02-18 12:16
So it's caused by a changes in version scheme for `ArmorKeywords.esm`.
Some use x.y.z like v8.6.0, and a few use x.y like v8.51.

```yaml
    msg:
      - <<: *obsolete
        condition: 'version("ArmorKeywords.esm", "8.5", <)'
``` 

Will evaluate to true for v8.6.0.

**Comment by MacSplody** [comment] 2020-02-18 12:27
@clydemack Fixed in https://github.com/loot/fallout4/commit/e882d8739e2a994aacd0d111725f557e4f95be1a.

**Closed as completed by MacSplody** 2020-02-18 12:27 UTC
