### ISSUE TITLE
Can't sort the load order with the new update

### ISSUE THREAD

**Issue by AZZOS** [loot/fallout4#69] opened 2018-06-02 18:08 UTC
Hi, as writed in the title the last up of LOOT is not working for me, this is the debug file:

(i already try this fix but it didn't work: "C:\Users\stefb\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again)

HALP!

[18:58:44.036969] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[18:58:44.070522] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[18:58:44.883440] [warning]: No masterlist present at C:\Users\stefb\AppData\Local\LOOT\Fallout4\masterlist.yaml
[18:58:57.865575] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[18:58:57.866151] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[18:58:57.866759] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\stefb\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
[18:59:31.256045] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[18:59:31.256104] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[18:59:31.256529] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\stefb\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
[19:00:19.538324] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[19:00:19.538382] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[19:00:19.538929] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\stefb\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
[19:00:24.484483] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[19:00:24.484555] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[19:00:24.485356] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\stefb\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
[19:00:47.925207] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[19:00:47.925263] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[19:00:47.925826] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\stefb\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)

**Comment by Ortham** [comment] 2018-06-02 18:13
This is a duplicate of loot/loot#956, see there for more information.

**Closed as completed by Ortham** 2018-06-02 18:13 UTC
Labels: duplicate
