### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by AlonmifexMaximus** [loot/fallout4#5] opened 2015-12-22 22:19 UTC
Caused when applying Sort Decision to LO's. 

Error code: 1; libloadorder failed to set the load order. Details: "C:\Users\alonl\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error

**Comment by unforbidable** [comment] 2015-12-23 07:30
See loot/loot#518.

**Comment by Ortham** [comment] 2015-12-23 09:00
Yes, this is a duplicate of the above linked issue (I edited the post to tidy up the link), so closing this.

**Closed as completed by Ortham** 2015-12-23 09:00 UTC
Labels: duplicate
