### ISSUE TITLE
loot can't download and/or update the masterlist

### ISSUE THREAD

**Issue by Buffmutti** [loot/fallout4#60] opened 2018-02-23 06:42 UTC
I'm using loot Version 0.12.3 (build bfd8ef0d) right now and i can't download a masterlist for fallout 4. I had this issue already with the previous version. With the previous version i had a masterlist and whenever i tried to sort the loadorder i got a errormessage which told me that i could check the LOOTDebugLog.txt, but that file was always empty. Today i updated to the newest version and now i have no masterlist and get again that errormessage, but this time there is some information in the LOOTDebugLog.txt.

[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1750687/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2018-02-23 07:56
Duplicate of loot/loot#882.

**Closed as completed by Ortham** 2018-02-23 07:56 UTC
Labels: duplicate
