### ISSUE TITLE
Error LOOTDebugLog.txt 

### ISSUE THREAD

**Issue by zp3nz3r** [loot/fallout4#44] opened 2017-07-09 12:30 UTC
I went through the installer, made sure everything was ticked and installed in fallout 4 folder. Loot launches after "installation is complete". I click sort plugins and when I click apply, the "Error LOOTDebugLog.txt" comes up and tells me to check the  LOOTDebugLog.txt in the main menu. I thought that relaunching LOOT would do the trick and low and behold, LOOT didn't install at all even though I successfully went through the installer.

[CEFDebugLog.txt](https://github.com/loot/fallout4/files/1133725/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/fallout4/files/1133726/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1133727/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2017-07-09 12:32
> [22:01:51.421908] [error]: libloadorder failed to set the load order. Details: "C:\Users\Spencer\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error: Libloadorder error


This is probably because your `plugins.txt` is read-only.

**Comment by zp3nz3r** [comment] 2017-07-09 12:40
Could you please tell me how to change this? And thanks for the reply.

**Comment by Ortham** [comment] 2017-07-09 12:48
[Let me Google that for you](http://lmgtfy.com/?q=how+to+make+a+file+not+read-only). I'm more than willing to help you out with LOOT, but there are a lot of things you're better off searching for yourself.

**Comment by zp3nz3r** [comment] 2017-07-09 12:54
I found it, but it's not set to read only.

**Comment by Ortham** [comment] 2017-07-09 12:59
Hmm, does it work if you run LOOT as an administrator?

**Comment by zp3nz3r** [comment] 2017-07-09 13:04
I ran the installer as an administrator and nothing.

**Comment by Ortham** [comment] 2017-07-09 13:10
Not the installer, the LOOT application.

**Comment by zp3nz3r** [comment] 2017-07-09 13:16
Remember when I said that LOOT doesn't actually install, even though I went through the installer. I tick the box so that LOOT auto-launches after installation. I can't actually locate it in the installation folder. The default location in the installer is steamapps>common>fallout4

**Comment by zp3nz3r** [comment] 2017-07-09 13:20
Because I can't locate the application in the installation folder, I have to reinstall LOOT each time and tick the auto-launch box.

**Comment by Ortham** [comment] 2017-07-09 13:41
> I can't actually locate it in the installation folder. The default location in the installer is steamapps>common>fallout4

Check in  `C:\Program Files (x86)\LOOT` (or `C:\Program Files\LOOT` on 32-bit Windows), that's the real default. IIRC the installer will change the location based on previous installs' Registry keys though.

**Comment by zp3nz3r** [comment] 2017-07-09 14:14
Nothing. It's funny because when I browse the destination location for installation I see a LOOT folder 
under Program Files (x86) However when I later open up Program Files (x86) it isn't there. I tried installing it in the LOOT folder and again, nothing.

**Comment by zp3nz3r** [comment] 2017-07-09 15:53
I opened the debug location throught LOOT menu and went to C:\Program Files (x86)\LOOT
and tried to run the application as an administrator. Strange how I can't access the LOOT folder the conventional way. I had the same preoblem when I tried to report the Error LOOTDebugLog.txt I couldn't access the appdata files, so I had to copy and paste the content into new docs.

**Comment by zp3nz3r** [comment] 2017-07-09 15:56
Any further assistance would be apreciated.

**Comment by Ortham** [comment] 2017-07-09 16:46
Do older releases of LOOT work?

**Comment by zp3nz3r** [comment] 2017-07-10 04:50
It was working before, yes. I'm not sure about older versions.

**Comment by Freso** [comment] 2017-07-10 15:45
@zp3nz3r Can you trying using LOOT 0.10.3 and report whether that's working? Also, what's your [Windows build number](https://lmddgtfy.net/?q=how%20do%20i%20find%20my%20windows%20build%20number%3F)?

**Comment by Ortham** [comment] 2017-07-10 17:01
Note that you can find all LOOT releases [here](https://github.com/loot/loot/releases).

**Comment by Ortham** [comment] 2018-05-27 07:14
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Closed as completed by Ortham** 2018-05-27 07:14 UTC
Labels: awaiting-feedback
