### ISSUE TITLE
Loot Cant detect Plugins For Fallout 4

### ISSUE THREAD

**Issue by Arvezia** [loot/fallout4#68] opened 2018-05-24 23:21 UTC
So this is the first time i use LOOT,when i open it, LOOT just detect my base game and DLC .esm and not detect any of my mod plugin(its usually have .esp extension)
i use NMM for modding, so i try to move all of my mod to base game install path and reinstall it, but LOOT still dont detect all of my mod

**Comment by Arvezia** [comment] 2018-05-24 23:21
[06:14:59.648907] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[06:15:00.209767] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[06:17:13.181748] [error]: libloadorder failed to set the load order. Details: Access is denied. (os error 5)
[06:17:13.185006] [error]: Exception while executing query: libloadorder failed to set the load order. Details: Access is denied. (os error 5): Libloadorder error
[06:17:13.285112] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because your plugins.txt is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)

**Comment by Ortham** [comment] 2018-05-25 06:31
Duplicate of loot/loot#951, please don't open duplicate issues.

**Closed as completed by Ortham** 2018-05-25 06:31 UTC
Labels: duplicate
